### ISSUE TITLE
Have all arrays extend `ImmutableList` or `List`

### ISSUE THREAD

**Issue by Laxystem** [daniel-rusu/pods4k#4]
**Is your feature request related to a problematic scenario? Please describe.**

It's currently impossible to use your arrays within an existing codebase.

**Describe the solution you'd like**

Have each immutable array implement `ImmutableList`.

**Describe alternatives you've considered**

* Only implement `List` until KotlinX Immutable Collections is added into the stdlib, to prevent a dependency.

**Additional context**
Add any other context about the feature request here.

**Comment by Laxystem** [comment]
@daniel-rusu I understand. How about only having typed arrays implement `ImmutableList`, then? That's better than nothing.

I noticed the arrays themselves are codegenned; You could create a version of your library that depends on immutable collections for this, as including it as a dependency might be ridiculous.

**Comment by daniel-rusu** [comment]
I just did a quick test to better understand the impacts so I locally made `ImmutableArray<T>` implement `List<T>`.  Note that the `ImmutableList` interface extends the `List` interface so the results would have been the same (plus the additional dependency).  These are the problems that this introduced:

1. The extension functions that I defined for Immutable Arrays were overshadowed by the same functions from the Kotlin standard library that operate on lists, collections, or iterables (since the List interface extends those interfaces).  For example, calling `people.map { it.weightKg }` no longer produced an `ImmutableFloatArray`, but rather it produced a much less efficient `List<Float>`.  This would increase memory consumption, reduce performance, and also break the immutability guarantees that Immutable Arrays offer since immutability can be bypassed for the results of these operations.
2. Implementing the `List` interface forces me to include methods that should never be used with Immutable Arrays such as the `subList` method.  Users of this library should instead use dedicated methods or extension functions that are explicitly designed for Immutable Arrays otherwise they might accidentally find themselves back in the traditional list world with the associated memory and performance impacts.  But most importantly, if they're accidentally back to lists then further transformations would produce results that no longer meet the immutability guarantees that Immutable Arrays offer.
3. Having typed Immutable Arrays implement the List interface but not the other variants would result in a frustrating developer experience.  This is because operations on typed Immutable Arrays naturally transition to primitive versions to always use the most efficient option depending on the data type and operation being performed (eg. `people.map { it.weightKg }` produces an `ImmutableFloatArray`).  This would result in being able to directly pass the results to List APIs for some operations but not for others and this can even vary for the exact same operation but different data types (eg. `people.map { it.spouse }` produces an `ImmutableArray<Person>`).

So all things considered, I think it's best for users to explicitly use `asList()` or `toList()` when they want to cross over into the List world.

**Comment by daniel-rusu** [comment]
I added a section for working alongside List APIs:

https://github.com/daniel-rusu/pods4k/tree/main/immutable-arrays#interop-with-list-apis

This section includes an explanation of why Immutable Arrays shouldn't implement the `List` interface.

**Comment by Laxystem** [comment]
I see.

I'll link [this KEEP note](https://github.com/Kotlin/KEEP/blob/master/notes/value-classes.md) for future reference, though - it details Kotlin's plans to implement proper value class support, including a section about arrays.
